## Understanding `logits[:, -1, :]`

In [1]:
import numpy as np

# Create a 3D array with shape (2, 3, 4)
# This could represent:
# - 2 batches
# - 3 time steps
# - 4 features or classes
logits = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("Original logits shape:", logits.shape)
print("Original logits:\n", logits)

# Now let's apply our indexing
result = logits[:, -1, :]

print("\nResult shape:", result.shape)
print("Result:\n", result)

Original logits shape: (2, 3, 4)
Original logits:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Result shape: (2, 4)
Result:
 [[ 9 10 11 12]
 [21 22 23 24]]
